pip3 install  numpy
pip3 install astunparse
pip3 install  pandas
pip3 install xdict
pip3 install elist
pip3 install edict
pip3 install dlist
pip3 install tlist
pip3 install ltdict
pip3 install estring
pip3 install spaint
pip3 install rblk
pip3 install sldghmmr4nut
pip3 install qtable
pip3 install efdir
pip3 install navegador5
pip3 install nvhtml
pip3 install xxurl
pip3 install tytycss
pip3 install kukibanshee
pip3 install nvhead
pip3 install minidoc
pip3 install conjugar
